language: node_js

node_js:
  - "lts/*"

branches:
  except:
    - master

script:
  - npm run build

deploy:
  # Push the site to GitHub pages
  - provider: pages
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    local-dir: dist
    target_branch: master
    on:
      branch: develop

env:
  - secure: SDNahBeXj5iYGkF86+phbQz4icgJZmx31xKmf7S09HTlfyGpk6qCN6/Dr3xQeyRqlpJXQ6TcI2P2db0zbTCjZwj3DzKMwh8ei3Rhoze1sV9Yh/ZxFT+1D1PyG19otqm+wmyfX3Dsy8lppVd3MAMS9U//gkABgaMi25drqaM9CJovoItR2eey5lTPWq7JcrmESF6iwZ2vder1n2yCeAFduDoiZz3qpmqXBEzvi3bYTb/GczcMSzmbPUXU0skIX55uZnNXN4amalx1IIkW1iYI24M25T4aVAMs4/bD8ZywayAUChsVbnICVwMccxGwqgYCd2ln+XT3mWSeEJzHHMaKElt8bPHlx+3Nnsqm7vh3RmejJ4XObDboruYzuh1JXD5xS2mHCJXHsdytYuoeWedt9I5BrH8xrUELpwrXKwNTwq7FN074FwkIo+B56oHoKk8/BYt8pvF2tSL4BjtTklZKTSS3hOdXrv0q2/0rN2UG4cXArtVMf0GApnhdRkMMtsQ6x2voDKMBfe09nBJTzjlveVCiAisTNk93+jRr10CHJdFY0i7LNOIeRx6nBi5iEoD8NaURBSuyVV5xWbEZItKh8l6vesvJeI7tKD/zBkqdd9J2qlfOPFiC/tp3EErQFrqWkBOH/u5cjpC00vSKXMAXeKza/OPnTha08kZTAVs1G4M=
